"""The persisted workflow seam for local RCA runs."""

from __future__ import annotations

from dataclasses import dataclass, replace
import json
from pathlib import Path
from typing import Protocol
from uuid import uuid4

from .evidence import AttachmentEvidence, AttachmentMetadata, CollectionEvidence, EvidencePackage
from .jira_intelligence import ArtifactDescriptor, JiraIntelligenceClient, JiraIntelligenceError
from .knowledge_base import KBPassage, KBSelection, KnowledgeBase, KnowledgeBaseError
from .model_runner import CopilotCliRunner, Evaluation, Hypothesis, ModelRunner, ModelRunnerError, RcaDraft, parse_analyst_output, parse_evaluator_output


class WorkflowTransitionError(ValueError):
    """Raised when a persisted RCA Run contains an illegal state change."""


_ALLOWED_NEXT_STATES = {
    "created": frozenset({"collected", "blocked"}),
    "collected": frozenset({"evidence_ready", "blocked"}),
    "evidence_ready": frozenset({"kb_ready", "blocked"}),
    "kb_ready": frozenset({"drafted", "blocked"}),
    "drafted": frozenset({"evaluated", "blocked"}),
    "evaluated": frozenset({"awaiting_decision"}),
    "awaiting_decision": frozenset({"completed"}),
}

_NEXT_STATES = {
    "created": "collected",
    "collected": "evidence_ready",
    "evidence_ready": "kb_ready",
    "kb_ready": "drafted",
    "drafted": "evaluated",
    "evaluated": "awaiting_decision",
    "awaiting_decision": "completed",
}
_TERMINAL_STATES = frozenset({"blocked", "completed"})
_ALLOWED_ATTACHMENT_SUFFIXES = frozenset(
    {".txt", ".log", ".json", ".xml", ".csv", ".md", ".js", ".yaml", ".yml"}
)


@dataclass(frozen=True)
class AttachmentLimits:
    """The bounded attachment evidence budget for one RCA Run."""

    per_file_bytes: int = 2 * 1024 * 1024
    aggregate_bytes: int = 8 * 1024 * 1024
    model_characters: int = 200_000

    def __post_init__(self) -> None:
        if self.per_file_bytes <= 0 or self.aggregate_bytes <= 0 or self.model_characters <= 0:
            raise ValueError("Attachment evidence limits must be positive.")


@dataclass(frozen=True)
class RcaRun:
    """One locally persisted RCA Run."""

    run_id: str
    issue_key: str
    model: str
    state: str
    state_history: tuple[str, ...]
    report_path: Path
    writeback_decision: str
    collection_run_id: str | None
    kb_revision: str | None
    kb_passage_ids: tuple[str, ...]
    evaluation_result: str | None
    model_prompt: str
    jira_event_ids: tuple[str, ...]
    confirmed_observations: tuple[str, ...] = ()
    reported_claims: tuple[str, ...] = ()
    missing_evidence: tuple[str, ...] = ()
    components: tuple[str, ...] = ()
    labels: tuple[str, ...] = ()
    kb_domains: tuple[str, ...] = ()
    kb_passages: tuple[KBPassage, ...] = ()
    product_version: str | None = None
    kb_version_applicability: str = "unverified"
    blocked_reason: str | None = None
    attachment_metadata: tuple[AttachmentMetadata, ...] = ()
    attachments: tuple[AttachmentEvidence, ...] = ()
    analyst_draft: RcaDraft | None = None
    evaluation: Evaluation | None = None
    analyst_prompt: str | None = None
    evaluator_prompt: str | None = None
    analyst_raw_output: str | None = None
    evaluator_raw_output: str | None = None
    analyst_model: str | None = None
    evaluator_model: str | None = None
    writeback_event_ids: tuple[str, ...] = ()


@dataclass(frozen=True)
class FixtureProvenance:
    """The deterministic evidence identifiers generated by Fixture Runner."""

    evaluation_result: str | None
    model_prompt: str
    jira_event_ids: tuple[str, ...]


class RunStore(Protocol):
    """Persistence required by the RcaWorkflow seam."""

    def create(
        self, issue_key: str, model: str, provenance: FixtureProvenance
    ) -> RcaRun: ...

    def load(self, run_id: str) -> RcaRun: ...

    def save(self, run: RcaRun) -> None: ...


class FixtureRunner(Protocol):
    """Deterministic source of local-only Fixture Runner evidence."""

    def provenance_for(self, issue_key: str) -> FixtureProvenance: ...


class _DefaultFixtureRunner:
    def provenance_for(self, issue_key: str) -> FixtureProvenance:
        return FixtureProvenance(
            evaluation_result="needs_evidence",
            model_prompt="fixture-v1",
            jira_event_ids=(),
        )


class _DefaultFixtureJiraIntelligence:
    """Local-only evidence for direct workflow use; the CLI injects Jira Intelligence."""

    def collect_or_reuse(self, issue_key: str, rca_run_id: str) -> CollectionEvidence:
        collection_run_id = f"fixture-collection-{issue_key}"
        return CollectionEvidence(
            collection_run_id=collection_run_id,
            evidence=EvidencePackage(
                collection_run_id=collection_run_id,
                confirmed_observations=("Fixture Collection Run only; live Jira collection has not run.",),
                reported_claims=(),
                missing_evidence=("Live Jira evidence is intentionally unavailable in fixture mode.",),
                components=(),
                labels=(),
            ),
        )

    def list_artifacts(self, issue_key: str, collection_run_id: str) -> tuple[ArtifactDescriptor, ...]:
        return ()

    def read_artifact(
        self, issue_key: str, collection_run_id: str, reference: str, max_bytes: int
    ) -> bytes:
        raise JiraIntelligenceError("Fixture Jira Intelligence has no Attachment Evidence.")

    def post_status_comment(self, *_arguments: object, **_keywords: object) -> tuple[str, ...]:
        raise JiraIntelligenceError("Fixture Jira Intelligence cannot write back to Jira.")

    def upload_analysis_report(self, *_arguments: object, **_keywords: object) -> tuple[str, ...]:
        raise JiraIntelligenceError("Fixture Jira Intelligence cannot write back to Jira.")


class _DefaultFixtureKnowledgeBase:
    """Local-only guidance for direct workflow use; the CLI injects the configured KB."""

    def retrieve(self, evidence: EvidencePackage, product_version: str | None) -> KBSelection:
        return KBSelection(
            kb_revision="fixture-kb-v1",
            version_applicability="unverified" if product_version is None else "not_verified",
            domain_ids=(),
            passages=(),
        )


class _LocalRunStore:
    def __init__(self, output_root: Path) -> None:
        self._output_root = output_root

    def create(
        self, issue_key: str, model: str, provenance: FixtureProvenance
    ) -> RcaRun:
        run_id = str(uuid4())
        run = RcaRun(
            run_id=run_id,
            issue_key=issue_key,
            model=model,
            state="created",
            state_history=("created",),
            report_path=self._output_root / run_id / "rca-report.md",
            writeback_decision="not_requested",
            collection_run_id=None,
            kb_revision=None,
            kb_passage_ids=(),
            evaluation_result=provenance.evaluation_result,
            model_prompt=provenance.model_prompt,
            jira_event_ids=provenance.jira_event_ids,
        )
        self.save(run)
        return run

    def load(self, run_id: str) -> RcaRun:
        record_path = self._output_root / run_id / "run.json"
        try:
            record = json.loads(record_path.read_text(encoding="utf-8"))
        except FileNotFoundError as error:
            raise FileNotFoundError(f"RCA Run not found: {run_id}") from error
        return RcaRun(
            run_id=record["run_id"],
            issue_key=record["issue_key"],
            model=record["model"],
            state=record["state"],
            state_history=tuple(record["state_history"]),
            report_path=self._output_root / run_id / record["report_file"],
            writeback_decision=record["writeback_decision"],
            collection_run_id=record.get("collection_run_id"),
            kb_revision=record.get("kb_revision"),
            kb_passage_ids=tuple(record["kb_passage_ids"]),
            evaluation_result=record["evaluation_result"],
            model_prompt=record["model_prompt"],
            jira_event_ids=tuple(record["jira_event_ids"]),
            confirmed_observations=tuple(record.get("confirmed_observations", ())),
            reported_claims=tuple(record.get("reported_claims", ())),
            missing_evidence=tuple(record.get("missing_evidence", ())),
            components=tuple(record.get("components", ())),
            labels=tuple(record.get("labels", ())),
            kb_domains=tuple(record.get("kb_domains", ())),
            kb_passages=tuple(KBPassage(**passage) for passage in record.get("kb_passages", ())),
            product_version=record.get("product_version"),
            kb_version_applicability=record.get("kb_version_applicability", "unverified"),
            blocked_reason=record.get("blocked_reason"),
            attachment_metadata=tuple(
                AttachmentMetadata(**metadata) for metadata in record.get("attachment_metadata", ())
            ),
            attachments=tuple(AttachmentEvidence(**attachment) for attachment in record.get("attachments", ())),
            analyst_draft=_draft_from_record(record.get("analyst_draft")),
            evaluation=_evaluation_from_record(record.get("evaluation")),
            analyst_prompt=_invocation_value(record, "analyst", "prompt"),
            evaluator_prompt=_invocation_value(record, "evaluator", "prompt"),
            analyst_raw_output=_invocation_value(record, "analyst", "raw_output"),
            evaluator_raw_output=_invocation_value(record, "evaluator", "raw_output"),
            analyst_model=_invocation_value(record, "analyst", "model"),
            evaluator_model=_invocation_value(record, "evaluator", "model"),
            writeback_event_ids=tuple(record.get("writeback_event_ids", ())),
        )

    def save(self, run: RcaRun) -> None:
        run_directory = self._output_root / run.run_id
        run_directory.mkdir(parents=True, exist_ok=True)
        record = {
            "run_id": run.run_id,
            "issue_key": run.issue_key,
            "model": run.model,
            "state": run.state,
            "state_history": list(run.state_history),
            "report_file": run.report_path.name,
            "writeback_decision": run.writeback_decision,
            "writeback_event_ids": list(run.writeback_event_ids),
            "collection_run_id": run.collection_run_id,
            "kb_revision": run.kb_revision,
            "kb_passage_ids": list(run.kb_passage_ids),
            "evaluation_result": run.evaluation_result,
            "model_prompt": run.model_prompt,
            "jira_event_ids": list(run.jira_event_ids),
            "confirmed_observations": list(run.confirmed_observations),
            "reported_claims": list(run.reported_claims),
            "missing_evidence": list(run.missing_evidence),
            "components": list(run.components),
            "labels": list(run.labels),
            "kb_domains": list(run.kb_domains),
            "kb_passages": [
                {
                    "citation_id": passage.citation_id,
                    "domain_id": passage.domain_id,
                    "relative_path": passage.relative_path,
                    "text": passage.text,
                }
                for passage in run.kb_passages
            ],
            "product_version": run.product_version,
            "kb_version_applicability": run.kb_version_applicability,
            "blocked_reason": run.blocked_reason,
            "attachment_metadata": [
                {
                    "attachment_id": metadata.attachment_id,
                    "filename": metadata.filename,
                    "mime_type": metadata.mime_type,
                    "size": metadata.size,
                }
                for metadata in run.attachment_metadata
            ],
            "attachments": [
                {
                    "reference": attachment.reference,
                    "filename": attachment.filename,
                    "mime_type": attachment.mime_type,
                    "size": attachment.size,
                    "status": attachment.status,
                    "reason": attachment.reason,
                    "text": attachment.text,
                    "truncated": attachment.truncated,
                }
                for attachment in run.attachments
            ],
            "analyst_draft": _draft_record(run.analyst_draft),
            "evaluation": _evaluation_record(run.evaluation),
            "model_invocations": {
                "analyst": _invocation_record(run.analyst_model, run.analyst_prompt, run.analyst_raw_output),
                "evaluator": _invocation_record(run.evaluator_model, run.evaluator_prompt, run.evaluator_raw_output),
            },
        }
        (run_directory / "run.json").write_text(
            json.dumps(record, indent=2) + "\n", encoding="utf-8"
        )


class RcaWorkflow:
    """Coordinates the state machine exposed to the CLI and tests."""

    def __init__(
        self,
        output_root: Path | None = None,
        *,
        run_store: RunStore | None = None,
        fixture_runner: FixtureRunner | None = None,
        model_runner: ModelRunner | None = None,
        jira_intelligence_client: JiraIntelligenceClient | None = None,
        knowledge_base: KnowledgeBase | None = None,
        attachment_limits: AttachmentLimits | None = None,
        analysis_root: Path | None = None,
    ) -> None:
        if run_store is None:
            if output_root is None:
                raise ValueError("output_root is required when run_store is not provided")
            run_store = _LocalRunStore(output_root)
        self._store = run_store
        self._fixture_runner = fixture_runner or _DefaultFixtureRunner()
        self._jira_intelligence_client = jira_intelligence_client or _DefaultFixtureJiraIntelligence()
        self._knowledge_base = knowledge_base or _DefaultFixtureKnowledgeBase()
        self._attachment_limits = attachment_limits or AttachmentLimits()
        self._model_runner = model_runner or CopilotCliRunner()
        self._analysis_root = analysis_root

    def run(self, issue_key: str, model: str, product_version: str | None = None) -> RcaRun:
        """Start and finish one Fixture Runner RCA Run using collected evidence."""
        if model not in {"fixture", "copilot"}:
            raise ValueError("model must be fixture or copilot")
        if not issue_key.strip():
            raise ValueError("issue_key must not be empty")
        if model == "copilot":
            self._model_runner.preflight()
        provenance = self._fixture_runner.provenance_for(issue_key) if model == "fixture" else FixtureProvenance(
            evaluation_result=None, model_prompt="", jira_event_ids=()
        )
        return self._continue_run(
            self._store.create(
                issue_key,
                model,
                provenance,
            ),
            product_version,
        )

    def resume(self, run_id: str) -> RcaRun:
        """Continue a saved Fixture Runner run without repeating saved stages."""
        run = self._store.load(run_id)
        self._validate_history(run)
        if run.model not in {"fixture", "copilot"}:
            raise ValueError("RCA Run has an unsupported model")
        if run.model == "copilot" and run.state in {"kb_ready", "drafted"}:
            self._model_runner.preflight()
        return self._continue_run(run, run.product_version)

    def get(self, run_id: str) -> RcaRun:
        """Read one persisted RCA Run without advancing it."""
        run = self._store.load(run_id)
        self._validate_history(run)
        return run

    def confirm_writeback(self, run_id: str, *, approved: bool) -> RcaRun:
        """Persist a terminal decision and perform only the allowed Jira mutation."""
        run = self.get(run_id)
        if run.state != "completed" or run.evaluation_result not in {"passed", "needs_evidence", "escalated"}:
            raise WorkflowTransitionError("Writeback requires a completed RCA Run with an Evaluation Result.")
        if run.writeback_decision == "declined":
            return run
        if run.writeback_decision == "approved" and not approved:
            return run
        if not approved:
            decided = replace(run, writeback_decision="declined")
            self._update_report_writeback_decision(decided)
            self._store.save(decided)
            return decided

        approved_run = replace(run, writeback_decision="approved")
        self._update_report_writeback_decision(approved_run)
        self._store.save(approved_run)
        collection_run_id = _required_collection_run_id(approved_run)
        approval_reference = f"terminal-approval-{approved_run.run_id}"
        if approved_run.evaluation_result == "passed":
            self._stage_analysis_report(approved_run)
        comment_events = self._jira_intelligence_client.post_status_comment(
            approved_run.issue_key,
            _status_comment(approved_run),
            collection_run_id=collection_run_id,
            orchestration_run_id=approved_run.run_id,
            approval_reference=approval_reference,
            idempotency_key=f"rca-comment-{approved_run.run_id}",
        )
        written = replace(approved_run, writeback_event_ids=comment_events)
        self._store.save(written)
        if approved_run.evaluation_result == "passed":
            attachment_events = self._jira_intelligence_client.upload_analysis_report(
                approved_run.issue_key,
                collection_run_id=collection_run_id,
                orchestration_run_id=approved_run.run_id,
                approval_reference=approval_reference,
                idempotency_key=f"rca-attachment-{approved_run.run_id}",
            )
            written = replace(written, writeback_event_ids=(*comment_events, *attachment_events))
        self._store.save(written)
        return written

    def _continue_run(self, run: RcaRun, product_version: str | None) -> RcaRun:
        if run.state == "created":
            try:
                collection = self._jira_intelligence_client.collect_or_reuse(run.issue_key, run.run_id)
            except JiraIntelligenceError as error:
                return self._block(run, str(error))
            run = replace(
                run,
                collection_run_id=collection.collection_run_id,
                confirmed_observations=collection.evidence.confirmed_observations,
                reported_claims=collection.evidence.reported_claims,
                missing_evidence=collection.evidence.missing_evidence,
                components=collection.evidence.components,
                labels=collection.evidence.labels,
                attachment_metadata=collection.attachment_metadata,
            )
            run = self._advance(run)
        if run.state == "collected":
            run = replace(run, attachments=self._collect_attachment_evidence(run))
            run = self._advance(run)
        if run.state == "evidence_ready":
            try:
                selection = self._knowledge_base.retrieve(self._evidence_from(run), product_version)
            except KnowledgeBaseError as error:
                return self._block(run, str(error))
            run = replace(
                run,
                kb_revision=selection.kb_revision,
                kb_passage_ids=tuple(passage.citation_id for passage in selection.passages),
                kb_domains=selection.domain_ids,
                kb_passages=selection.passages,
                product_version=product_version,
                kb_version_applicability=selection.version_applicability,
            )
            run = self._advance(run)
        if run.state == "kb_ready" and run.model == "copilot":
            try:
                invocation = self._model_runner.run_analyst(
                    self._evidence_from(run), run.kb_passages, product_version, run.kb_version_applicability
                )
                draft = parse_analyst_output(invocation.raw_output, self._evidence_from(run), run.kb_passages)
            except ModelRunnerError as error:
                return self._block(run, str(error))
            run = replace(run, analyst_draft=draft, analyst_model=invocation.model, analyst_prompt=invocation.prompt,
                          analyst_raw_output=invocation.raw_output, model_prompt=invocation.prompt)
            run = self._advance(run)
        if run.state == "drafted" and run.model == "copilot":
            if run.analyst_draft is None:
                return self._block(run, "RCA Run has no persisted Analyst draft.")
            try:
                invocation = self._model_runner.run_evaluator(
                    run.analyst_draft, self._evidence_from(run), run.kb_passages,
                    product_version, run.kb_version_applicability,
                )
                evaluation = parse_evaluator_output(invocation.raw_output)
            except ModelRunnerError as error:
                return self._block(run, str(error))
            run = replace(run, evaluation=evaluation, evaluation_result=evaluation.result, evaluator_model=invocation.model,
                          evaluator_prompt=invocation.prompt, evaluator_raw_output=invocation.raw_output)
            run = self._advance(run)
        while run.state not in _TERMINAL_STATES:
            run = self._advance(run)
        if run.state == "completed" and not run.report_path.exists():
            self._render_report(run)
        self._store.save(run)
        return run

    def _block(self, run: RcaRun, reason: str) -> RcaRun:
        blocked = replace(
            run,
            state="blocked",
            state_history=(*run.state_history, "blocked"),
            evaluation_result=None,
            blocked_reason=reason,
        )
        self._store.save(blocked)
        return blocked

    def _evidence_from(self, run: RcaRun) -> EvidencePackage:
        return EvidencePackage(
            collection_run_id=_required_collection_run_id(run),
            confirmed_observations=run.confirmed_observations,
            reported_claims=run.reported_claims,
            missing_evidence=run.missing_evidence,
            components=run.components,
            labels=run.labels,
            attachments=tuple(attachment for attachment in run.attachments if attachment.status == "included"),
        )

    def _collect_attachment_evidence(self, run: RcaRun) -> tuple[AttachmentEvidence, ...]:
        collection_run_id = _required_collection_run_id(run)
        try:
            artifacts = self._jira_intelligence_client.list_artifacts(run.issue_key, collection_run_id)
        except JiraIntelligenceError:
            if run.attachment_metadata:
                return tuple(
                    AttachmentEvidence(
                        reference=None,
                        filename=metadata.filename,
                        mime_type=metadata.mime_type,
                        size=metadata.size,
                        status="excluded",
                        reason="inventory_unavailable",
                    )
                    for metadata in run.attachment_metadata
                )
            return (
                AttachmentEvidence(
                    reference=None,
                    filename="Attachment inventory",
                    mime_type=None,
                    size=0,
                    status="excluded",
                    reason="inventory_unavailable",
                ),
            )

        used_metadata_indexes: set[int] = set()
        attachments: list[AttachmentEvidence] = []
        aggregate_bytes = 0
        model_characters = 0
        for artifact in sorted(artifacts, key=lambda descriptor: descriptor.reference):
            matching_metadata = _matching_metadata_index(
                run.attachment_metadata, used_metadata_indexes, artifact
            )
            if matching_metadata is not None:
                used_metadata_indexes.add(matching_metadata)
            excluded_reason = _artifact_exclusion_reason(artifact, self._attachment_limits, aggregate_bytes)
            if excluded_reason is not None:
                attachments.append(_excluded_attachment(artifact, excluded_reason))
                continue
            remaining_characters = self._attachment_limits.model_characters - model_characters
            if remaining_characters <= 0:
                attachments.append(_excluded_attachment(artifact, "model_package_limit_exceeded"))
                continue
            try:
                content = self._jira_intelligence_client.read_artifact(
                    run.issue_key,
                    collection_run_id,
                    artifact.reference,
                    self._attachment_limits.per_file_bytes,
                )
            except JiraIntelligenceError:
                attachments.append(_excluded_attachment(artifact, "unavailable"))
                continue
            if len(content) > self._attachment_limits.per_file_bytes:
                attachments.append(_excluded_attachment(artifact, "per_file_limit_exceeded"))
                continue
            if aggregate_bytes + len(content) > self._attachment_limits.aggregate_bytes:
                attachments.append(_excluded_attachment(artifact, "aggregate_limit_exceeded"))
                continue
            try:
                text = content.decode("utf-8")
            except UnicodeDecodeError:
                attachments.append(_excluded_attachment(artifact, "not_utf8_text"))
                continue
            excerpt = text[:remaining_characters]
            attachments.append(
                AttachmentEvidence(
                    reference=artifact.reference,
                    filename=artifact.filename,
                    mime_type=artifact.mime_type,
                    size=len(content),
                    status="included",
                    text=excerpt,
                    truncated=len(excerpt) < len(text),
                )
            )
            aggregate_bytes += len(content)
            model_characters += len(excerpt)

        for index, metadata in enumerate(run.attachment_metadata):
            if index not in used_metadata_indexes:
                attachments.append(
                    AttachmentEvidence(
                        reference=None,
                        filename=metadata.filename,
                        mime_type=metadata.mime_type,
                        size=metadata.size,
                        status="excluded",
                        reason="missing_from_collection",
                    )
                )
        return tuple(attachments)

    def _advance(self, run: RcaRun) -> RcaRun:
        try:
            next_state = _NEXT_STATES[run.state]
        except KeyError as error:
            raise WorkflowTransitionError(
                f"RCA Run cannot advance from terminal or unknown state: {run.state}"
            ) from error
        advanced = replace(
            run,
            state=next_state,
            state_history=(*run.state_history, next_state),
        )
        self._store.save(advanced)
        return advanced

    def _validate_history(self, run: RcaRun) -> None:
        if not run.state_history or run.state_history[0] != "created":
            raise WorkflowTransitionError("Workflow State history must begin at created")
        if run.state_history[-1] != run.state:
            raise WorkflowTransitionError("Workflow State must match the persisted state history")
        for current, next_state in zip(run.state_history, run.state_history[1:]):
            if next_state not in _ALLOWED_NEXT_STATES.get(current, frozenset()):
                raise WorkflowTransitionError(
                    f"Illegal Workflow State transition: {current} -> {next_state}"
                )

    def _render_report(self, run: RcaRun) -> None:
        if run.model == "copilot":
            self._render_live_report(run)
            return
        run.report_path.write_text(
            "# RCA Report: " + run.issue_key + "\n\n"
            "## Outcome and confidence\n\n"
            f"Evaluation Result: {run.evaluation_result}. Fixture analysis has demo-only confidence.\n\n"
            + _markdown_list("Jira observations", run.confirmed_observations)
            + _markdown_list("Reported but unverified claims", run.reported_claims)
            + _markdown_list(
                "KB guidance and citations",
                tuple(
                    f"[{passage.citation_id}] {passage.relative_path}: {passage.text.splitlines()[0]}"
                    for passage in run.kb_passages
                ),
            )
            + _attachment_markdown(run.attachments)
            +
            "## Hypotheses\n\n"
            "- Fixture hypothesis: confirm the live evidence before accepting this Hypothesis.\n\n"
            + _markdown_list("Unknowns and missing evidence", run.missing_evidence)
            +
            "## Next actions\n\n"
            "- Re-run with live adapters in a later ticket.\n\n"
            "## Provenance\n\n"
            f"- RCA Run: {run.run_id}\n"
            "- Model Runner: fixture\n"
            f"- Collection Run: {run.collection_run_id}\n"
            f"- KB revision: {run.kb_revision}\n"
            f"- Product Version: {run.product_version or 'not provided'}\n"
            f"- KB version applicability: {run.kb_version_applicability}\n"
            f"- Prompt: {run.model_prompt}\n"
            f"- Evaluation Result: {run.evaluation_result}\n"
            "- Writeback Decision: not requested\n",
            encoding="utf-8",
        )

    def _update_report_writeback_decision(self, run: RcaRun) -> None:
        if not run.report_path.exists():
            return
        report = run.report_path.read_text(encoding="utf-8")
        run.report_path.write_text(
            report.replace("- Writeback Decision: not requested", f"- Writeback Decision: {run.writeback_decision}"),
            encoding="utf-8",
        )

    def _stage_analysis_report(self, run: RcaRun) -> None:
        if self._analysis_root is None:
            raise JiraIntelligenceError(
                "RCA_ORCHESTRATOR_JIRA_INTELLIGENCE_UPLOAD_SOURCE_ROOT must be configured for a passed RCA Report writeback."
            )
        analysis_directory = self._analysis_root / run.issue_key / "runs" / _required_collection_run_id(run) / "analysis"
        analysis_directory.mkdir(parents=True, exist_ok=True)
        analysis_report = analysis_directory / "rca-report.md"
        unexpected = tuple(
            path
            for path in analysis_directory.iterdir()
            if path != analysis_report and path.name != ".jira-intelligence"
        )
        if unexpected:
            raise JiraIntelligenceError("Jira Intelligence analysis directory contains files outside this RCA Report.")
        analysis_report.write_text(run.report_path.read_text(encoding="utf-8"), encoding="utf-8")

    def _render_live_report(self, run: RcaRun) -> None:
        assert run.analyst_draft is not None
        assert run.evaluation is not None
        hypotheses = tuple(
            f"{item.title} (confidence {item.confidence:.2f}; supports: {', '.join(item.supporting_evidence)}; "
            f"contradicts: {', '.join(item.contradicting_evidence) or 'none'}; unknowns: {', '.join(item.unknowns) or 'none'})"
            for item in run.analyst_draft.hypotheses
        )
        run.report_path.write_text(
            "# RCA Report: " + run.issue_key + "\n\n"
            "## Outcome and confidence\n\n"
            f"Evaluation Result: {run.evaluation.result}.\n"
            f"KB version applicability: {run.kb_version_applicability}.\n\n"
            + _markdown_list("Jira observations", run.confirmed_observations)
            + _markdown_list("Reported but unverified claims", run.reported_claims)
            + _markdown_list("KB guidance and citations", tuple(f"[{item.citation_id}] {item.relative_path}: {item.text.splitlines()[0]}" for item in run.kb_passages))
            + _attachment_markdown(run.attachments)
            + _markdown_list("Hypotheses", hypotheses)
            + _markdown_list("Most likely explanation", (run.analyst_draft.most_likely_explanation,) if run.analyst_draft.most_likely_explanation else ())
            + _markdown_list("Unknowns and missing evidence", (*run.missing_evidence, *run.analyst_draft.unknowns, *run.evaluation.unknowns))
            + _markdown_list("Evaluation evidence gaps and contradictions", (*run.evaluation.citation_gaps, *run.evaluation.contradictions))
            + _markdown_list("Next actions", run.analyst_draft.recommended_actions)
            + "## Provenance\n\n"
            f"- RCA Run: {run.run_id}\n- Model Runner: {run.model}\n- Collection Run: {run.collection_run_id}\n"
            f"- KB revision: {run.kb_revision}\n- Product Version: {run.product_version or 'not provided'}\n"
            f"- KB version applicability: {run.kb_version_applicability}\n- Evaluation Result: {run.evaluation.result}\n"
            "- Writeback Decision: not requested\n",
            encoding="utf-8",
        )


def _markdown_list(heading: str, values: tuple[str, ...]) -> str:
    body = "\n".join(f"- {value}" for value in values) if values else "- None."
    return f"## {heading}\n\n{body}\n\n"


def _required_collection_run_id(run: RcaRun) -> str:
    if run.collection_run_id is None:
        raise WorkflowTransitionError("Evidence Package requires a Collection Run.")
    return run.collection_run_id


def _status_comment(run: RcaRun) -> str:
    assert run.evaluation_result is not None
    result = run.evaluation_result.replace("_", " ")
    if run.evaluation_result == "passed":
        return (
            f"RCA Orchestrator status: Evaluation Result is {result}. "
            "The evidence-cited RCA Report is attached."
        )
    return (
        f"RCA Orchestrator status: Evaluation Result is {result}. "
        "No RCA Report is attached; this result requires follow-up before a root-cause conclusion."
    )


def _matching_metadata_index(
    metadata: tuple[AttachmentMetadata, ...],
    used_indexes: set[int],
    artifact: ArtifactDescriptor,
) -> int | None:
    for index, candidate in enumerate(metadata):
        if index not in used_indexes and (
            candidate.filename,
            candidate.mime_type,
            candidate.size,
        ) == (artifact.filename, artifact.mime_type, artifact.size):
            return index
    return None


def _artifact_exclusion_reason(
    artifact: ArtifactDescriptor, limits: AttachmentLimits, aggregate_bytes: int
) -> str | None:
    if artifact.kind != "jira_attachment":
        return "not_a_jira_attachment"
    if Path(artifact.filename).suffix.lower() not in _ALLOWED_ATTACHMENT_SUFFIXES:
        return "unsupported_file_type"
    if artifact.size > limits.per_file_bytes:
        return "per_file_limit_exceeded"
    if aggregate_bytes + artifact.size > limits.aggregate_bytes:
        return "aggregate_limit_exceeded"
    return None


def _excluded_attachment(artifact: ArtifactDescriptor, reason: str) -> AttachmentEvidence:
    return AttachmentEvidence(
        reference=artifact.reference,
        filename=artifact.filename,
        mime_type=artifact.mime_type,
        size=artifact.size,
        status="excluded",
        reason=reason,
    )


def _attachment_markdown(attachments: tuple[AttachmentEvidence, ...]) -> str:
    used = tuple(attachment for attachment in attachments if attachment.status == "included")
    excluded = tuple(attachment for attachment in attachments if attachment.status == "excluded")
    return (
        "## Attachment Evidence\n\n"
        + _markdown_list("Attachment Evidence used", tuple(_used_attachment_line(attachment) for attachment in used))
        + _markdown_list(
            "Attachment Evidence unanalysed",
            tuple(_excluded_attachment_line(attachment) for attachment in excluded),
        )
    )


def _used_attachment_line(attachment: AttachmentEvidence) -> str:
    truncation = "; truncated" if attachment.truncated else ""
    return (
        f"{attachment.filename} [{attachment.reference}]: included excerpt "
        f"({len(attachment.text or '')} characters{truncation})"
    )


def _excluded_attachment_line(attachment: AttachmentEvidence) -> str:
    reference = f" [{attachment.reference}]" if attachment.reference is not None else ""
    return f"{attachment.filename}{reference}: {attachment.reason}"


def _draft_record(draft: RcaDraft | None) -> dict[str, object] | None:
    if draft is None:
        return None
    return {"hypotheses": [{"title": item.title, "supporting_evidence": list(item.supporting_evidence), "contradicting_evidence": list(item.contradicting_evidence), "unknowns": list(item.unknowns), "confidence": item.confidence} for item in draft.hypotheses], "most_likely_explanation": draft.most_likely_explanation, "unknowns": list(draft.unknowns), "recommended_actions": list(draft.recommended_actions)}


def _draft_from_record(record: object) -> RcaDraft | None:
    if not isinstance(record, dict):
        return None
    try:
        return RcaDraft(tuple(Hypothesis(title=item["title"], supporting_evidence=tuple(item["supporting_evidence"]), contradicting_evidence=tuple(item["contradicting_evidence"]), unknowns=tuple(item["unknowns"]), confidence=float(item["confidence"])) for item in record["hypotheses"]), record.get("most_likely_explanation"), tuple(record["unknowns"]), tuple(record["recommended_actions"]))
    except (KeyError, TypeError, ValueError):
        raise WorkflowTransitionError("RCA Run has an invalid persisted Analyst draft.") from None


def _evaluation_record(evaluation: Evaluation | None) -> dict[str, object] | None:
    if evaluation is None:
        return None
    return {"result": evaluation.result, "citation_gaps": list(evaluation.citation_gaps), "contradictions": list(evaluation.contradictions), "unknowns": list(evaluation.unknowns), "rationale": evaluation.rationale}


def _evaluation_from_record(record: object) -> Evaluation | None:
    if not isinstance(record, dict):
        return None
    try:
        return Evaluation(record["result"], tuple(record["citation_gaps"]), tuple(record["contradictions"]), tuple(record["unknowns"]), record["rationale"])
    except (KeyError, TypeError):
        raise WorkflowTransitionError("RCA Run has an invalid persisted Evaluation.") from None


def _invocation_record(model: str | None, prompt: str | None, raw_output: str | None) -> dict[str, str] | None:
    if model is None or prompt is None or raw_output is None:
        return None
    return {"model": model, "prompt": prompt, "raw_output": raw_output}


def _invocation_value(record: dict[str, object], role: str, field: str) -> str | None:
    invocations = record.get("model_invocations")
    if not isinstance(invocations, dict):
        return None
    invocation = invocations.get(role)
    if not isinstance(invocation, dict):
        return None
    value = invocation.get(field)
    return value if isinstance(value, str) else None
