"""The persisted workflow seam for local RCA runs."""

from __future__ import annotations

from dataclasses import dataclass, replace
import json
from pathlib import Path
from typing import Protocol
from uuid import uuid4

from .evidence import CollectionEvidence, EvidencePackage
from .jira_intelligence import JiraIntelligenceClient, JiraIntelligenceError
from .knowledge_base import KBPassage, KBSelection, KnowledgeBase, KnowledgeBaseError


class WorkflowTransitionError(ValueError):
    """Raised when a persisted RCA Run contains an illegal state change."""


_ALLOWED_NEXT_STATES = {
    "created": frozenset({"collected", "blocked"}),
    "collected": frozenset({"evidence_ready", "blocked"}),
    "evidence_ready": frozenset({"kb_ready", "blocked"}),
    "kb_ready": frozenset({"drafted", "blocked"}),
    "drafted": frozenset({"evaluated"}),
    "evaluated": frozenset({"awaiting_decision"}),
    "awaiting_decision": frozenset({"completed"}),
}

_FIXTURE_NEXT_STATES = {
    "created": "collected",
    "collected": "evidence_ready",
    "evidence_ready": "kb_ready",
    "kb_ready": "drafted",
    "drafted": "evaluated",
    "evaluated": "awaiting_decision",
    "awaiting_decision": "completed",
}
_TERMINAL_STATES = frozenset({"blocked", "completed"})


@dataclass(frozen=True)
class RcaRun:
    """One locally persisted RCA Run."""

    run_id: str
    issue_key: str
    model: str
    state: str
    state_history: tuple[str, ...]
    report_path: Path
    writeback_decision: str
    collection_run_id: str | None
    kb_revision: str | None
    kb_passage_ids: tuple[str, ...]
    evaluation_result: str | None
    model_prompt: str
    jira_event_ids: tuple[str, ...]
    confirmed_observations: tuple[str, ...] = ()
    reported_claims: tuple[str, ...] = ()
    missing_evidence: tuple[str, ...] = ()
    components: tuple[str, ...] = ()
    labels: tuple[str, ...] = ()
    kb_domains: tuple[str, ...] = ()
    kb_passages: tuple[KBPassage, ...] = ()
    product_version: str | None = None
    kb_version_applicability: str = "unverified"
    blocked_reason: str | None = None


@dataclass(frozen=True)
class FixtureProvenance:
    """The deterministic evidence identifiers generated by Fixture Runner."""

    evaluation_result: str
    model_prompt: str
    jira_event_ids: tuple[str, ...]


class RunStore(Protocol):
    """Persistence required by the RcaWorkflow seam."""

    def create(
        self, issue_key: str, model: str, provenance: FixtureProvenance
    ) -> RcaRun: ...

    def load(self, run_id: str) -> RcaRun: ...

    def save(self, run: RcaRun) -> None: ...


class FixtureRunner(Protocol):
    """Deterministic source of local-only Fixture Runner evidence."""

    def provenance_for(self, issue_key: str) -> FixtureProvenance: ...


class _DefaultFixtureRunner:
    def provenance_for(self, issue_key: str) -> FixtureProvenance:
        return FixtureProvenance(
            evaluation_result="needs_evidence",
            model_prompt="fixture-v1",
            jira_event_ids=(),
        )


class _DefaultFixtureJiraIntelligence:
    """Local-only evidence for direct workflow use; the CLI injects Jira Intelligence."""

    def collect_or_reuse(self, issue_key: str, rca_run_id: str) -> CollectionEvidence:
        collection_run_id = f"fixture-collection-{issue_key}"
        return CollectionEvidence(
            collection_run_id=collection_run_id,
            evidence=EvidencePackage(
                collection_run_id=collection_run_id,
                confirmed_observations=("Fixture Collection Run only; live Jira collection has not run.",),
                reported_claims=(),
                missing_evidence=("Live Jira evidence is intentionally unavailable in fixture mode.",),
                components=(),
                labels=(),
            ),
        )


class _DefaultFixtureKnowledgeBase:
    """Local-only guidance for direct workflow use; the CLI injects the configured KB."""

    def retrieve(self, evidence: EvidencePackage, product_version: str | None) -> KBSelection:
        return KBSelection(
            kb_revision="fixture-kb-v1",
            version_applicability="unverified" if product_version is None else "not_verified",
            domain_ids=(),
            passages=(),
        )


class _LocalRunStore:
    def __init__(self, output_root: Path) -> None:
        self._output_root = output_root

    def create(
        self, issue_key: str, model: str, provenance: FixtureProvenance
    ) -> RcaRun:
        run_id = str(uuid4())
        run = RcaRun(
            run_id=run_id,
            issue_key=issue_key,
            model=model,
            state="created",
            state_history=("created",),
            report_path=self._output_root / run_id / "rca-report.md",
            writeback_decision="not_requested",
            collection_run_id=None,
            kb_revision=None,
            kb_passage_ids=(),
            evaluation_result=provenance.evaluation_result,
            model_prompt=provenance.model_prompt,
            jira_event_ids=provenance.jira_event_ids,
        )
        self.save(run)
        return run

    def load(self, run_id: str) -> RcaRun:
        record_path = self._output_root / run_id / "run.json"
        try:
            record = json.loads(record_path.read_text(encoding="utf-8"))
        except FileNotFoundError as error:
            raise FileNotFoundError(f"RCA Run not found: {run_id}") from error
        return RcaRun(
            run_id=record["run_id"],
            issue_key=record["issue_key"],
            model=record["model"],
            state=record["state"],
            state_history=tuple(record["state_history"]),
            report_path=self._output_root / run_id / record["report_file"],
            writeback_decision=record["writeback_decision"],
            collection_run_id=record.get("collection_run_id"),
            kb_revision=record.get("kb_revision"),
            kb_passage_ids=tuple(record["kb_passage_ids"]),
            evaluation_result=record["evaluation_result"],
            model_prompt=record["model_prompt"],
            jira_event_ids=tuple(record["jira_event_ids"]),
            confirmed_observations=tuple(record.get("confirmed_observations", ())),
            reported_claims=tuple(record.get("reported_claims", ())),
            missing_evidence=tuple(record.get("missing_evidence", ())),
            components=tuple(record.get("components", ())),
            labels=tuple(record.get("labels", ())),
            kb_domains=tuple(record.get("kb_domains", ())),
            kb_passages=tuple(KBPassage(**passage) for passage in record.get("kb_passages", ())),
            product_version=record.get("product_version"),
            kb_version_applicability=record.get("kb_version_applicability", "unverified"),
            blocked_reason=record.get("blocked_reason"),
        )

    def save(self, run: RcaRun) -> None:
        run_directory = self._output_root / run.run_id
        run_directory.mkdir(parents=True, exist_ok=True)
        record = {
            "run_id": run.run_id,
            "issue_key": run.issue_key,
            "model": run.model,
            "state": run.state,
            "state_history": list(run.state_history),
            "report_file": run.report_path.name,
            "writeback_decision": run.writeback_decision,
            "collection_run_id": run.collection_run_id,
            "kb_revision": run.kb_revision,
            "kb_passage_ids": list(run.kb_passage_ids),
            "evaluation_result": run.evaluation_result,
            "model_prompt": run.model_prompt,
            "jira_event_ids": list(run.jira_event_ids),
            "confirmed_observations": list(run.confirmed_observations),
            "reported_claims": list(run.reported_claims),
            "missing_evidence": list(run.missing_evidence),
            "components": list(run.components),
            "labels": list(run.labels),
            "kb_domains": list(run.kb_domains),
            "kb_passages": [
                {
                    "citation_id": passage.citation_id,
                    "domain_id": passage.domain_id,
                    "relative_path": passage.relative_path,
                    "text": passage.text,
                }
                for passage in run.kb_passages
            ],
            "product_version": run.product_version,
            "kb_version_applicability": run.kb_version_applicability,
            "blocked_reason": run.blocked_reason,
        }
        (run_directory / "run.json").write_text(
            json.dumps(record, indent=2) + "\n", encoding="utf-8"
        )


class RcaWorkflow:
    """Coordinates the state machine exposed to the CLI and tests."""

    def __init__(
        self,
        output_root: Path | None = None,
        *,
        run_store: RunStore | None = None,
        fixture_runner: FixtureRunner | None = None,
        jira_intelligence_client: JiraIntelligenceClient | None = None,
        knowledge_base: KnowledgeBase | None = None,
    ) -> None:
        if run_store is None:
            if output_root is None:
                raise ValueError("output_root is required when run_store is not provided")
            run_store = _LocalRunStore(output_root)
        self._store = run_store
        self._fixture_runner = fixture_runner or _DefaultFixtureRunner()
        self._jira_intelligence_client = jira_intelligence_client or _DefaultFixtureJiraIntelligence()
        self._knowledge_base = knowledge_base or _DefaultFixtureKnowledgeBase()

    def run(self, issue_key: str, model: str, product_version: str | None = None) -> RcaRun:
        """Start and finish one Fixture Runner RCA Run using collected evidence."""
        if model != "fixture":
            raise ValueError("Ticket 2 supports only the explicit fixture model")
        if not issue_key.strip():
            raise ValueError("issue_key must not be empty")
        return self._continue_fixture_run(
            self._store.create(
                issue_key,
                model,
                self._fixture_runner.provenance_for(issue_key),
            ),
            product_version,
        )

    def resume(self, run_id: str) -> RcaRun:
        """Continue a saved Fixture Runner run without repeating saved stages."""
        run = self._store.load(run_id)
        self._validate_history(run)
        if run.model != "fixture":
            raise ValueError("Ticket 2 can resume only fixture runs")
        return self._continue_fixture_run(run, run.product_version)

    def get(self, run_id: str) -> RcaRun:
        """Read one persisted RCA Run without advancing it."""
        run = self._store.load(run_id)
        self._validate_history(run)
        return run

    def _continue_fixture_run(self, run: RcaRun, product_version: str | None) -> RcaRun:
        if run.state == "created":
            try:
                collection = self._jira_intelligence_client.collect_or_reuse(run.issue_key, run.run_id)
            except JiraIntelligenceError as error:
                return self._block(run, str(error))
            run = replace(
                run,
                collection_run_id=collection.collection_run_id,
                confirmed_observations=collection.evidence.confirmed_observations,
                reported_claims=collection.evidence.reported_claims,
                missing_evidence=collection.evidence.missing_evidence,
                components=collection.evidence.components,
                labels=collection.evidence.labels,
            )
            run = self._advance(run)
        if run.state == "collected":
            run = self._advance(run)
        if run.state == "evidence_ready":
            try:
                selection = self._knowledge_base.retrieve(self._evidence_from(run), product_version)
            except KnowledgeBaseError as error:
                return self._block(run, str(error))
            run = replace(
                run,
                kb_revision=selection.kb_revision,
                kb_passage_ids=tuple(passage.citation_id for passage in selection.passages),
                kb_domains=selection.domain_ids,
                kb_passages=selection.passages,
                product_version=product_version,
                kb_version_applicability=selection.version_applicability,
            )
            run = self._advance(run)
        while run.state not in _TERMINAL_STATES:
            run = self._advance(run)
        if run.state == "completed" and not run.report_path.exists():
            self._render_report(run)
        self._store.save(run)
        return run

    def _block(self, run: RcaRun, reason: str) -> RcaRun:
        blocked = replace(
            run,
            state="blocked",
            state_history=(*run.state_history, "blocked"),
            evaluation_result=None,
            blocked_reason=reason,
        )
        self._store.save(blocked)
        return blocked

    def _evidence_from(self, run: RcaRun) -> EvidencePackage:
        return EvidencePackage(
            collection_run_id=_required_collection_run_id(run),
            confirmed_observations=run.confirmed_observations,
            reported_claims=run.reported_claims,
            missing_evidence=run.missing_evidence,
            components=run.components,
            labels=run.labels,
        )

    def _advance(self, run: RcaRun) -> RcaRun:
        try:
            next_state = _FIXTURE_NEXT_STATES[run.state]
        except KeyError as error:
            raise WorkflowTransitionError(
                f"Fixture run cannot advance from terminal or unknown state: {run.state}"
            ) from error
        advanced = replace(
            run,
            state=next_state,
            state_history=(*run.state_history, next_state),
        )
        self._store.save(advanced)
        return advanced

    def _validate_history(self, run: RcaRun) -> None:
        if not run.state_history or run.state_history[0] != "created":
            raise WorkflowTransitionError("Workflow State history must begin at created")
        if run.state_history[-1] != run.state:
            raise WorkflowTransitionError("Workflow State must match the persisted state history")
        for current, next_state in zip(run.state_history, run.state_history[1:]):
            if next_state not in _ALLOWED_NEXT_STATES.get(current, frozenset()):
                raise WorkflowTransitionError(
                    f"Illegal Workflow State transition: {current} -> {next_state}"
                )

    def _render_report(self, run: RcaRun) -> None:
        run.report_path.write_text(
            "# RCA Report: " + run.issue_key + "\n\n"
            "## Outcome and confidence\n\n"
            f"Evaluation Result: {run.evaluation_result}. Fixture analysis has demo-only confidence.\n\n"
            + _markdown_list("Jira observations", run.confirmed_observations)
            + _markdown_list("Reported but unverified claims", run.reported_claims)
            + _markdown_list(
                "KB guidance and citations",
                tuple(
                    f"[{passage.citation_id}] {passage.relative_path}: {passage.text.splitlines()[0]}"
                    for passage in run.kb_passages
                ),
            )
            +
            "## Hypotheses\n\n"
            "- Fixture hypothesis: confirm the live evidence before accepting this Hypothesis.\n\n"
            + _markdown_list("Unknowns and missing evidence", run.missing_evidence)
            +
            "## Next actions\n\n"
            "- Re-run with live adapters in a later ticket.\n\n"
            "## Provenance\n\n"
            f"- RCA Run: {run.run_id}\n"
            "- Model Runner: fixture\n"
            f"- Collection Run: {run.collection_run_id}\n"
            f"- KB revision: {run.kb_revision}\n"
            f"- Product Version: {run.product_version or 'not provided'}\n"
            f"- KB version applicability: {run.kb_version_applicability}\n"
            f"- Prompt: {run.model_prompt}\n"
            f"- Evaluation Result: {run.evaluation_result}\n"
            "- Writeback Decision: not requested\n",
            encoding="utf-8",
        )


def _markdown_list(heading: str, values: tuple[str, ...]) -> str:
    body = "\n".join(f"- {value}" for value in values) if values else "- None."
    return f"## {heading}\n\n{body}\n\n"


def _required_collection_run_id(run: RcaRun) -> str:
    if run.collection_run_id is None:
        raise WorkflowTransitionError("Evidence Package requires a Collection Run.")
    return run.collection_run_id
